// import { useTranslation } from 'next-i18next';
// import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

// import imgLogo from '~/assets/images/points-bg.png';
import { CssBaseline, List, ListItem, ListItemText } from '@mui/material';
import Tracker from '~/shared/track';

import styles from '../styles/Home.module.css';

import type { NextPage } from 'next';

const Home: NextPage = props => {
  const router = useRouter();
  const str = `$${router.asPath}`;
  const token =
    'color/surface/1/fg/default/idle txt/us-en/fluid-root/card-label-base bg/surface/1/fg/default/idle';

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <span agToken={token}></span>

      <div
        agToken="color/blue/spectrum/15 txt/us-en/fluid-root/utility-sm "
        className="bg-red-100 text-blue-500">
        color/surface/1/fg/default/idle
      </div>
    </div>
  );
};

export const getStaticProps = async ({ locale }: any) => ({
  props: {
    // ...await serverSideTranslations(locale, ['common', 'footer']),
  }
});

export default Home;
